services:
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./alembic/:/app/alembic/
      - ./alembic.ini:/app/alembic.ini
      - ./scripts/:/app/scripts/
    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: ./app/app
        - action: rebuild
          path: ./requirements.txt
          target: ./app/requirements.txt
        - action: sync+restart
          path: ./main.py
          target: ./app/main.py
    environment:
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis-db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres
    env_file:
      - .env
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "1234:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis-db:
    image: redis
    ports:
      - "6555:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER: "on"
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" --address ":9000" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  createbucket:
      image: minio/mc
      depends_on:
        - minio
      entrypoint: >
        /bin/sh -c "
        /usr/bin/mc config host add --api s3v4 s3 http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
        /usr/bin/mc mb s3/gozem/;
        /usr/bin/mc anonymous set download s3/gozem/;
        "
      networks:
        - app-network
  ngnix:
    image: nginx:alpine

    ports:
      - "80:80"  # Redirige les requêtes vers le conteneur NGINX
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Ajoute la configuration de NGINX
    depends_on:
      - api
      - minio
    networks:
      - app-network

volumes:
  db-data:
  redis_data:
  minio_data:

networks:
  app-network:
    driver: bridge


